import '@/styles/globals.scss';
import '@/styles/globals.module.scss';

const metadata = {
  title: 'UPX - SmartCities',
  description: 'Generated by create next app',
}

export {metadata};

function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
        <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
        <script noModule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
      </body>
    </html>
  )
}

export default RootLayout;
